---
environment:
  CGO_ENABLED: "0"
  GOARCH: amd64
  GOOS: linux
  GOTOOLCHAIN: local
kind: pipeline
name: build-1.22-alpine3.20-amd64
platform:
  arch: amd64
  os: linux
steps:
- commands:
  - apk update
  - apk add --no-cache git
  - mkdir .bin
  - go build -v -o ./.bin/go-away ./cmd/go-away
  - go build -v -o ./.bin/test-wasm-runtime ./cmd/test-wasm-runtime
  image: golang:1.22-alpine3.20
  name: build
- commands:
  - ./.bin/test-wasm-runtime -wasm ./embed/challenge/js-pow-sha256/runtime/runtime.wasm
    -make-challenge ./embed/challenge/js-pow-sha256/test/make-challenge.json -make-challenge-out
    ./embed/challenge/js-pow-sha256/test/make-challenge-out.json -verify-challenge
    ./embed/challenge/js-pow-sha256/test/verify-challenge.json -verify-challenge-out
    0
  depends_on:
  - build
  image: alpine:3.20
  name: test-wasm-success
- commands:
  - ./.bin/test-wasm-runtime -wasm ./embed/challenge/js-pow-sha256/runtime/runtime.wasm
    -make-challenge ./embed/challenge/js-pow-sha256/test/make-challenge.json -make-challenge-out
    ./embed/challenge/js-pow-sha256/test/make-challenge-out.json -verify-challenge
    ./embed/challenge/js-pow-sha256/test/verify-challenge-fail.json -verify-challenge-out
    1
  depends_on:
  - build
  image: alpine:3.20
  name: test-wasm-fail
type: docker
---
environment:
  CGO_ENABLED: "0"
  GOARCH: arm64
  GOOS: linux
  GOTOOLCHAIN: local
kind: pipeline
name: build-1.22-alpine3.20-arm64
platform:
  arch: arm64
  os: linux
steps:
- commands:
  - apk update
  - apk add --no-cache git
  - mkdir .bin
  - go build -v -o ./.bin/go-away ./cmd/go-away
  - go build -v -o ./.bin/test-wasm-runtime ./cmd/test-wasm-runtime
  image: golang:1.22-alpine3.20
  name: build
- commands:
  - ./.bin/test-wasm-runtime -wasm ./embed/challenge/js-pow-sha256/runtime/runtime.wasm
    -make-challenge ./embed/challenge/js-pow-sha256/test/make-challenge.json -make-challenge-out
    ./embed/challenge/js-pow-sha256/test/make-challenge-out.json -verify-challenge
    ./embed/challenge/js-pow-sha256/test/verify-challenge.json -verify-challenge-out
    0
  depends_on:
  - build
  image: alpine:3.20
  name: test-wasm-success
- commands:
  - ./.bin/test-wasm-runtime -wasm ./embed/challenge/js-pow-sha256/runtime/runtime.wasm
    -make-challenge ./embed/challenge/js-pow-sha256/test/make-challenge.json -make-challenge-out
    ./embed/challenge/js-pow-sha256/test/make-challenge-out.json -verify-challenge
    ./embed/challenge/js-pow-sha256/test/verify-challenge-fail.json -verify-challenge-out
    1
  depends_on:
  - build
  image: alpine:3.20
  name: test-wasm-fail
type: docker
---
kind: signature
hmac: 86b713999f4663f87be2637c70be316b9f89fbe2e905ae73802dc1357cd91596

...
